name: Publish Github Action
on: [push]
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Github Action
    steps:
      - uses: actions/checkout@v4
      - id: publish-action
        uses: github-actions-publish/publish-action@main
        with:
          tag: v1
